# Generated by Django 6.0 on 2026-03-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('ecity', models.CharField(max_length=100)),
                ('edept', models.CharField(max_length=100)),
                ('esal', models.IntegerField()),
                ('epassword', models.CharField(max_length=256)),
                ('erole', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
